[package]
name = "pavex_static_files"
version = "0.4.1"
edition = "2024"

[dependencies]
mime_guess = "2.0.5"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
